### ISSUE TITLE
Wrong async handling -> possible unobserved exception

### ISSUE THREAD

**Issue by kebisekjan** [microsoft/vs-streamjsonrpc#1067]
![image](https://github.com/user-attachments/assets/b4dd8675-9331-4a7f-8170-59387ba4853a)

**Comment by AArnott** [comment]
There is no bug here. Adding `async` and `await` modifiers here would just create another touch point when an exception is thrown where it has to be handled and rethrown by the async state machine. By propagating the `ValueTask<JsonRpcMessage>` directly, it requires less machinery and a slightly faster runtime.

**Comment by kebisekjan** [comment]
The problem that I'm observing:

**Subscribe:**
TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedException;

**Unobserved exception:**
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> MessagePack.MessagePackSerializationException: Failed to deserialize StreamJsonRpc.Protocol.JsonRpcMessage value. ---> MessagePack.MessagePackSerializationException: Unexpected msgpack code 0 (positive fixint) encountered.
   at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.TryReadMapHeader(Int32& count)
   at MessagePack.MessagePackReader.ReadMapHeader()
   at StreamJsonRpc.MessagePackFormatter.JsonRpcMessageFormatter.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](ReadOnlySequence`1& byteSequence, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at StreamJsonRpc.MessagePackFormatter.Deserialize(ReadOnlySequence`1 contentBuffer)
   at StreamJsonRpc.PipeMessageHandler.<DeserializeMessageAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.LengthHeaderMessageHandler.<ReadCoreAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.MessageHandlerBase.<ReadAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StreamJsonRpc.JsonRpc.<ReadAndHandleRequestsAsync>d__172.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) MessagePack.MessagePackSerializationException: Failed to deserialize StreamJsonRpc.Protocol.JsonRpcMessage value. ---> MessagePack.MessagePackSerializationException: Unexpected msgpack code 0 (positive fixint) encountered.
   at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.TryReadMapHeader(Int32& count)
   at MessagePack.MessagePackReader.ReadMapHeader()
   at StreamJsonRpc.MessagePackFormatter.JsonRpcMessageFormatter.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](ReadOnlySequence`1& byteSequence, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at StreamJsonRpc.MessagePackFormatter.Deserialize(ReadOnlySequence`1 contentBuffer)
   at StreamJsonRpc.PipeMessageHandler.<DeserializeMessageAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.LengthHeaderMessageHandler.<ReadCoreAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.MessageHandlerBase.<ReadAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StreamJsonRpc.JsonRpc.<ReadAndHandleRequestsAsync>d__172.MoveNext()<---

**Comment by AArnott** [comment]
The changes you proposed would not solve that issue. If you can share the exact version of StreamJsonRpc that threw that exception though, I can look up what those bottom two frames are to see if there is a way for the application to observe these exceptions. If there isn't, there may be a bug that needs to be fixed another way.

**Comment by kebisekjan** [comment]
We are using StreamJsonRpc 2.17.11

**Comment by AArnott** [comment]
Thanks. I see what's going on now. No real defect here, but we *do* have an unobserved task fault here, which if it's causing you concern, we can fix since it's a simple change.

**Comment by kebisekjan** [comment]
Thank you for your help.

**Comment by AArnott** [comment]
Sounds like the remote party is sending messages that do not use HTTP headers. So you should either change which handler you're using locally, or change the remote party.
