### ISSUE TITLE
Disposal of marhsallable object followed by disposal of jsonRpc on client leads to InvalidOperationException on server

### ISSUE THREAD

**Issue by ni28** [microsoft/vs-streamjsonrpc#1087]
Sometimes I'm getting the following exception on server side on 'await jsonRpc.Completion' when jsonRpc is disposed just after disposal of marshallable object on client side:

      System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.List`1.Enumerator.MoveNext()
         at StreamJsonRpc.Reflection.RpcTargetInfo.DisposeAsync()
         at StreamJsonRpc.JsonRpc.JsonRpcDisconnectedShutdownAsync(JsonRpcDisconnectedEventArgs eventArgs)

I believe the reason is a race condition when accessing the localTargetObjectsToDispose field in the RpcTargetInfo class from different threads. There are other non-concurrent collections in the RpcTargetInfo that probably also need attention.

I created a stress test to reproduce this (attached). It may take a while to get the exception in the server console.

[vs-streamjsonrpc-test.zip](https://github.com/user-attachments/files/17506261/vs-streamjsonrpc-test.zip)

**Comment by AArnott** [comment]
Thank you for your report, investigation and repro! What an awesome bug report.

**Comment by AArnott** [comment]
@matteo-prosperi  I wonder if you could take a first look at this?

**Comment by drewnoakes** [comment]
Should this be closed after #1156?
