### ISSUE TITLE
Unstable test: AspNetCoreWebSocket_DisposeRpcThenCloseSocket

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#128]
From [this CI build](https://travis-ci.org/Microsoft/vs-streamjsonrpc/jobs/397855227#L512):

```
[xUnit.net 00:00:02.6542180]     WebSocketMessageHandlerTests.AspNetCoreWebSocket_DisposeRpcThenCloseSocket [FAIL]
Failed   WebSocketMessageHandlerTests.AspNetCoreWebSocket_DisposeRpcThenCloseSocket
Error Message:
 System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'Microsoft.AspNetCore.TestHost.TestWebSocket'.
Stack Trace:
   at Microsoft.AspNetCore.TestHost.TestWebSocket.ReceiverSenderBuffer.ThrowNoReceive()
   at Microsoft.AspNetCore.TestHost.TestWebSocket.ReceiverSenderBuffer.<ReceiveAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.TestWebSocket.<ReceiveAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.TestWebSocket.<CloseAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebSocketMessageHandlerTests.<AspNetCoreWebSocket_DisposeRpcThenCloseSocket>d__21.MoveNext() in /Users/travis/build/Microsoft/vs-streamjsonrpc/src/StreamJsonRpc.Tests/WebSocketMessageHandlerTests.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by AArnott** [comment]
And [again](https://travis-ci.org/Microsoft/vs-streamjsonrpc/jobs/397887497#L969)

**Comment by AArnott** [comment]
Not repro in a long time.

**Comment by AArnott** [comment]
It [just repro'd](https://dev.azure.com/azure-public/vside/_build/results?buildId=9552&view=ms.vss-test-web.build-test-results-tab&runId=1023476&resultId=100752&paneView=debug).

> System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'Microsoft.AspNetCore.TestHost.TestWebSocket'.
> Stack trace
  at Microsoft.AspNetCore.TestHost.TestWebSocket+ReceiverSenderBuffer.ThrowNoReceive () [0x00017] in <77a260297de442849a96a0f2080cd8d7>:0 
  at Microsoft.AspNetCore.TestHost.TestWebSocket+ReceiverSenderBuffer.ReceiveAsync (System.Threading.CancellationToken cancellationToken) [0x000b8] in <77a260297de442849a96a0f2080cd8d7>:0 
  at Microsoft.AspNetCore.TestHost.TestWebSocket.ReceiveAsync (System.ArraySegment`1[T] buffer, System.Threading.CancellationToken cancellationToken) [0x0009c] in <77a260297de442849a96a0f2080cd8d7>:0 
  at Microsoft.AspNetCore.TestHost.TestWebSocket.CloseAsync (System.Net.WebSockets.WebSocketCloseStatus closeStatus, System.String statusDescription, System.Threading.CancellationToken cancellationToken) [0x0011e] in <77a260297de442849a96a0f2080cd8d7>:0 
  at WebSocketMessageHandlerTests.AspNetCoreWebSocket_DisposeRpcThenCloseSocket () [0x00188] in <bb0ce0d46ed6415c9bb841ab78a3a73f>:0
