### ISSUE TITLE
Unstable test: InvokeWithCancellationAsync_CancellableMethodWithoutCancellationToken

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#132]
Failed [on Travis](https://travis-ci.org/Microsoft/vs-streamjsonrpc/jobs/398382060#L553):

```
[xUnit.net 00:00:12.8769420]     JsonRpcTests.InvokeWithCancellationAsync_CancellableMethodWithoutCancellationToken [FAIL]
Failed   JsonRpcTests.InvokeWithCancellationAsync_CancellableMethodWithoutCancellationToken
Error Message:
 Assert.True() Failure
Expected: True
Actual:   False
Stack Trace:
   at TestBase.CheckGCPressureAsync(Func`1 scenario, Int32 maxBytesAllocated, Int32 iterations, Int32 allowedAttempts) in /Users/travis/build/Microsoft/vs-streamjsonrpc/src/StreamJsonRpc.Tests/TestBase.cs:line 103
   at JsonRpcTests.InvokeWithCancellationAsync_CancellableMethodWithoutCancellationToken() in /Users/travis/build/Microsoft/vs-streamjsonrpc/src/StreamJsonRpc.Tests/JsonRpcTests.cs:line 731
--- End of stack trace from previous location where exception was thrown ---
Standard Output Messages:
 Attempt 1
 27260 bytes leaked per iteration.
 89019 bytes allocated per iteration (unlimited allowed).
 Attempt 2
 89462 bytes leaked per iteration.
 170832 bytes allocated per iteration (unlimited allowed).
 Attempt 3
 22 bytes leaked per iteration.
 26792 bytes allocated per iteration (unlimited allowed).
 Attempt 4
 10 bytes leaked per iteration.
 26855 bytes allocated per iteration (unlimited allowed).
 Attempt 5
 10 bytes leaked per iteration.
 26683 bytes allocated per iteration (unlimited allowed).
 Attempt 6
 10 bytes leaked per iteration.
 26963 bytes allocated per iteration (unlimited allowed).
 Attempt 7
 10 bytes leaked per iteration.
 26706 bytes allocated per iteration (unlimited allowed).
 Attempt 8
 10 bytes leaked per iteration.
 26931 bytes allocated per iteration (unlimited allowed).
 Attempt 9
 10 bytes leaked per iteration.
 26737 bytes allocated per iteration (unlimited allowed).
 Attempt 10
 10 bytes leaked per iteration.
 26857 bytes allocated per iteration (unlimited allowed).
```

**Comment by AArnott** [comment]
Not repro in a long time.
