### ISSUE TITLE
PerfTests.BurstInvokeMessages test fails sometimes

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#249]
From [this build](https://dev.azure.com/azure-public/vside/_build/results?buildId=4180&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=3367cfe7-6aa5-5a88-c888-e6814d74f6eb&lineStart=6967&lineEnd=7005&colStart=1&colEnd=1)

```
Failed   PerfTests.BurstInvokeMessages(serverStream: FullDuplexStream { BeforeWrite = null, CanRead = True, CanSeek = False, CanTimeout = False, CanWrite = True, ... }, clientStream: FullDuplexStream { BeforeWrite = null, CanRead = True, CanSeek = False, CanTimeout = False, CanWrite = True, ... })
Error Message:
 StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete.
Stack Trace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__88`1.MoveNext() in /__w/1/s/src/StreamJsonRpc/JsonRpc.cs:line 1128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PerfTests.<BurstInvokeMessages>d__6.MoveNext() in /__w/1/s/src/StreamJsonRpc.Tests/PerfTests.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Standard Output Messages:
 Server Critical: 13 : Connection closing (StreamError: Reading JSON RPC from the stream failed with BadRpcHeaderException: Header does not end with expected 
  character sequence: 
). StreamJsonRpc.BadRpcHeaderException: Header does not end with expected 
  character sequence: 
    at StreamJsonRpc.HeaderDelimitedMessageHandler.<ReadHeadersAsync>d__35.MoveNext() in /__w/1/s/src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs:line 441
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at StreamJsonRpc.HeaderDelimitedMessageHandler.<ReadCoreAsync>d__25.MoveNext() in /__w/1/s/src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs:line 171
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at StreamJsonRpc.MessageHandlerBase.<ReadAsync>d__14.MoveNext() in /__w/1/s/src/StreamJsonRpc/MessageHandlerBase.cs:line 93
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at StreamJsonRpc.JsonRpc.<ReadAndHandleRequestsAsync>d__98.MoveNext() in /__w/1/s/src/StreamJsonRpc/JsonRpc.cs:line 1603
```

**Comment by AArnott** [comment]
Not repro in a long time.
