### ISSUE TITLE
Unstable test: JsonRpcRemoteTargetTests.VerifyMethodOrderingIsNotGuaranteedAfterYielding

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#336]
The `JsonRpcRemoteTargetTests.VerifyMethodOrderingIsNotGuaranteedAfterYielding` [test failed](https://dev.azure.com/azure-public/vside/_build/results?buildId=7347&view=ms.vss-test-web.build-test-results-tab&runId=1010088&resultId=100349&paneView=debug), leading to #334's build validation to fail.

```
Error message
Assert.Equal() Failure
Expected: 3
Actual: 2

Stack trace
   at JsonRpcRemoteTargetTests.<VerifyMethodOrderingIsNotGuaranteedAfterYielding>d__23.MoveNext() in d:\a\1\s\src\StreamJsonRpc.Tests\JsonRpcRemoteTargetTests.cs:line 239
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by AArnott** [comment]
@tinaschrepfer can you please investigate and fix?
