### ISSUE TITLE
Unstable test: JsonRpcTests.CancelMessageSentWhileAwaitingResponse

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#35]
The test below failed [this appveyor build](https://ci.appveyor.com/project/AArnott/vs-streamjsonrpc/build/1.1.68+gb8b06b38be.R), then succeeded later on [a rebuild](https://ci.appveyor.com/project/AArnott/vs-streamjsonrpc/build/112) of the same commit.

```
JsonRpcTests.CancelMessageSentWhileAwaitingResponse [FAIL]
    Assert.Throws() Failure
    Expected: typeof(StreamJsonRpc.RemoteInvocationException)
    Actual:   typeof(System.TimeoutException): The operation has timed out.
    Stack Trace:
        at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
        at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__7`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

**Comment by AArnott** [comment]
Not repro in a long time.
