### ISSUE TITLE
ClientCanWriteAndReadFromTwoWayStream test causes test process to crash

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#493]
From [this build](https://dev.azure.com/azure-public/vside/_build/results?buildId=9287&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=68789f9d-d85a-56a9-7bdd-bb2657086c1e&l=601):

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: Returned bytes
Actual:   (null)
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 189
   at Xunit.Assert.Equal(String expected, String actual) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 175
   at DuplexPipeMarshalingTests.Server.<>c__DisplayClass22_0.<<ServerMethodThatWritesAndReadsFromTwoWayStream>b__0>d.MoveNext() in /Users/runner/work/1/s/src/StreamJsonRpc.Tests/DuplexPipeMarshalingTests.cs:line 924
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

The bizarre part is why this server's anonymous method throwing would lead to a process crash. We don't ever await this Task in an `async void` method.

**Comment by AArnott** [comment]
Ah! The `async void` is hidden. It's the delegate passed to `new Task` itself, since that only takes `Action` delegates. A threading analyzer would have caught this...
