### ISSUE TITLE
ServiceJsonRpcDescriptor.JsonRpcConnection.ConstructRpcClient<T> fails to create an instance

### ISSUE THREAD

**Issue by tmat** [microsoft/vs-streamjsonrpc#789]
When called with an interface that implements another interface like so `TypeLoadException` is thrown.

Assembly1:
```C#
internal class C
{
  internal interface ICallback : I
  {
  }
}
```

Assembly2:
```C#
[assembly: InternalsVisibleTo("Assembly1")]

internal interface I
{
   ValueTask<E> Get(D d, CancellationToken token);
}

internal class D
{
}

internal class E
{
}
```

```
Feature 'Convert tuple to struct refactoring' is currently unavailable due to an internal error. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Access is denied: 'D'.
       at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
       at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
       at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
       at StreamJsonRpc.ProxyGeneration.CreateParameterObjectType(ModuleBuilder moduleBuilder, ParameterInfo[] parameters)
       at StreamJsonRpc.ProxyGeneration.Get(TypeInfo serviceInterface)
       at StreamJsonRpc.JsonRpc.Attach[T](JsonRpcProxyOptions options)
       at Microsoft.ServiceHub.Framework.ServiceJsonRpcDescriptor.JsonRpcConnection.ConstructRpcClient[T]()
--- End of inner exception stack trace ---
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Microsoft.ServiceHub.Framework.ServiceRpcDescriptor.RpcConnection.ConstructRpcClient(Type interfaceType)
```

**Comment by AArnott** [comment]
Thanks for reporting. This is likely something we can fix.

**Comment by tmat** [comment]
Here: [ClassLibrary1.zip](https://github.com/microsoft/vs-streamjsonrpc/files/8875027/ClassLibrary1.zip)
Forgot a parameter.

I looked more into the workaround we have in Roslyn and turns out, after some additional refactoring having this working won't save that much, so it's not that high of a priority to get fixed.

Thanks!

**Comment by AArnott** [comment]
Bingo. I've got a test that repros the failure now. Thank you.
And thanks for the notice on reduced priority.
